# use php-fpm:7.2.6
FROM php:7.2.6-fpm

# install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" 
RUN php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" 
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');" 
RUN mv composer.phar /usr/local/bin/composer

WORKDIR /app
# add user
RUN adduser --uid 1000 --disabled-password --gecos '' web && \
    chown -R web:web /app

COPY scripts/create-instance.sh /tmp/
RUN chown web:web /tmp/create-instance.sh && \
    chmod 655 /tmp/create-instance.sh
USER web
# RUN /tmp/create-instance.sh
